### ISSUE TITLE
Consider using a python venv for running `freeze.py`

### ISSUE THREAD

**Issue by vhvb1989** [pamelafox/pamelafox-site#16]
Instead of asking folks to run `python3 -m pip install -r requirements-dev.txt` in the Readme,
consider updating `deploy.sh` to create a `venv` and use it to run `freeze.py`.

Here is an example of a similar case: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/prepdocs.sh#L18

**Comment by pamelafox** [comment]
Oh interesting. The requirements installation is needed in order to run the Flask app locally, and the Dev Container typically takes care of it. (This README is not as clearly worded as my azd templates, sorry). 

Ah, but if I put it inside freeze.py, then someone can deploy the app without needing to do local development steps. Yeah that's fair, I'll consider that.

**Comment by pamelafox** [comment]
Done!
